#!/usr/bin/env bash
# 
# Odisee(R)
# Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.
# Copyright (C) 2011-2012 art of coding UG (haftungsbeschränkt).
#
# Alle Rechte vorbehalten. Nutzung unterliegt Lizenzbedingungen.
# All rights reserved. Use is subject to license terms.
#

set -o nounset

#
# Start Java application server.
#
stop_tomcat() {
    cd ${ODISEE_HOME}
    # Stop application server
    ${CATALINA_HOME}/bin/shutdown.sh
}

#
# Stop Java application server.
#
start_tomcat() {
    cd ${ODISEE_HOME}
    # Start application server
    ${CATALINA_HOME}/bin/startup.sh
}

#
# Update web application
#
update_tomcat_war() {
    pushd ${ODISEE_HOME}/install 1>/dev/null
    if [ -d odisee -a -f odisee_*.zip ]
    then
        rm -rf odisee
    fi
    if [ -f odisee_*.zip ]
    then
        unzip -q odisee_*.zip
    fi
    if [ -f odisee/lib/odisee.war ]
    then
        cp odisee/lib/odisee.war .
    fi
    if [ -f odisee.war ]
    then
        rm -rf ${CATALINA_HOME}/webapps/odisee*
        cp odisee.war ${CATALINA_HOME}/webapps
    fi
    popd 1>/dev/null
}

#
# Stop Odisee OpenOffice instances
#
stop_ooo() {
    odictl -q stop
    pkill -9 soffice.bin
    rm -f ${ODISEE_HOME}/.libreoffice/*/.lock
}

#
# Start Odisee OpenOffice instances
#
start_ooo() {
    odictl -q start
}

#
# Update extensions: Odisee, THK_Report
#
update_extension() {
    sudo $OOO_HOME/program/unopkg remove --shared vnd.artofcoding.odisee.Odisee
    sudo $OOO_HOME/program/unopkg add --shared $ODISEE_HOME/install/Odisee.oxt
}

# Parse parameters
declare -A cmdopt
cmdopt[a]=false
cmdopt[e]=false
cmdopt[l]=false
cmdopt[r]=false
cmdopt[w]=false
while getopts ":aelrw" opt
do
    case $opt in
        a) cmdopt[a]=true ;;
        e) cmdopt[e]=true ;;
        l) cmdopt[l]=true ;;
        r) cmdopt[r]=true ;;
        w) cmdopt[w]=true ;;
        \?)
            echo "ODI-xxxx: Unknown option -$OPTARG"
        ;;
        :)
            case $OPTARG in
                o)
                    echo "ODI-xxxx: Option -$OPTARG needs an instance name as argument."
                    echo "ODI-xxxx: e.g. $ORIG_CMD Odisee.oxt"
                ;;
                *)
                    echo "ODI-xxxx: Option -$OPTARG needs an argument."
                ;;
            esac
            exit 1
        ;;
    esac
done

if [ x"${cmdopt[a]}" = x"true" ]
then
    stop_tomcat
    stop_ooo
    update_tomcat_war
    update_extension
    start_ooo
    start_tomcat
elif [ x"${cmdopt[e]}" = x"true" ]
then
    stop_tomcat
    stop_ooo
    update_extension
    start_ooo
    start_tomcat
elif [ x"${cmdopt[w]}" = x"true" ]
then
    stop_tomcat
    stop_ooo
    update_tomcat_war
    start_ooo
    start_tomcat
elif [ x"${cmdopt[r]}" = x"true" ]
then
    stop_tomcat
    sleep 5
    start_tomcat
fi
if [ x"${cmdopt[l]}" = x"true" ]
then
    less ${CATALINA_HOME}/logs/catalina.out
fi
exit 0
