#!/usr/bin/env bash
# 
# Odisee(R)
# Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.
# Copyright (C) 2011-2012 art of coding UG (haftungsbeschränkt).
#
# Alle Rechte vorbehalten. Nutzung unterliegt Lizenzbedingungen.
# All rights reserved. Use is subject to license terms.
#

#
# PLEASE DON'T CHANGE LINES BELOW
# UNLESS ADVISED BY ODISEE SUPPORT
#

# Determine script directory
case "$0" in
    ./*) SCRIPT_DIR=${PWD} ;;
    /*) SCRIPT_DIR=${0%/*} ;;
    */*) SCRIPT_DIR=${PWD}/${0%/*} ;;
    *) SCRIPT_DIR=${PWD} ;;
esac

#
# Directories.
#

if [ x"${ODISEE_HOME}" = x"" ]
then
    echo "Please set ODISEE_HOME"
    exit 1
fi

# Odisee
ODISEE_LIBEXEC=${ODISEE_HOME}/libexec
ODISEE_CONF=${ODISEE_HOME}/etc
ODISEE_INST=${ODISEE_CONF}/odiinst
ODISEE_OS_LIB=${ODISEE_LIBEXEC}/${ODISEE_OS}
ODISEE_VAR=${ODISEE_HOME}/var
ODISEE_LOG=${ODISEE_VAR}/log
ODISEE_TMP=${ODISEE_VAR}/tmp/ramdisk
ODISEE_TMP_RAMDISK_MB=${ODISEE_TMP_RAMDISK_MB:-16}
ODISEE_BACKUP_RAMDISK=${ODISEE_VAR}/backup/ramdisk
ODISEE_OOO_USERINST=${ODISEE_TMP}/user
ODISEE_SRC=${ODISEE_HOME}/src
ODISEE_EXT=${ODISEE_SRC}/extension

#
# Operating system.
#

ODISEE_FQHN=$(uname -n)
ODISEE_OS=$(uname -s)
ODISEE_ARCH=$(uname -m)

# OS-dependent
case "${ODISEE_OS}" in
    Darwin)
        SED=$(which gsed)
    ;;
esac

# Any OS
SED=${SED:-$(which sed)}
RSYNC=${RSYNC:-$(which rsync)}

# Check needed executables
_check_exeutable() {
    local e=$1
    if [ -z "${e}" -o ! -x ${e} ]
    then
        echo "Needed executable ${e} not found or not executable by $(whoami)."
        exit 1
    fi
}
_check_exeutable ${SED}
_check_exeutable ${RSYNC}

#
# Check .fonts directory
#
fonts=$HOME/.fonts
if [ ! -e "${fonts}" ] # does not exist
then
    ln -s ${ODISEE_HOME}/var/deploy/font ${fonts} 
fi

#
# Java
#

# Get JAVA_HOME
if [ -z "${JAVA_HOME}" ]
then
    case "${ODISEE_OS}" in
        Darwin)
            JAVA_HOME=$(/usr/libexec/java_home)
        ;;
        *)
            JAVA_HOME=$(which java)
        ;;
    esac
    # Fallback is libexec/os/arch/java
    JAVA_HOME=${JAVA_HOME:-$ODISEE_LIBEXEC/${ODISEE_OS}/${ODISEE_ARCH}/java}
fi
# Check if we can execute java
[ ! -x ${JAVA_HOME}/bin/java ] && unset JAVA_HOME

# Apache Ant
ANT_HOME=${ANT_HOME:-$ODISEE_LIBEXEC/ant}

# Groovy & Grails
GROOVY_HOME=${GROOVY_HOME:-$ODISEE_LIBEXEC/groovy}
GRAILS_HOME=${GRAILS_HOME:-$ODISEE_LIBEXEC/grails}

# Apache Tomcat
CATALINA_BASE=${CATALINA_BASE:-$ODISEE_LIBEXEC/tomcat}

# JVM options
ODISEE_JVM_MEMORY="-Xms64m -Xmx128m -XX:MaxPermSize=256m"
ODISEE_JVM_GC="-XX:+CMSClassUnloadingEnabled" # -XX:+CMSPermGenSweepingEnabled
ODISEE_TOMCAT_OPTS="-Dorg.apache.catalina.loader.WebappClassLoader.ENABLE_CLEAR_REFERENCES=false -Ddisable.auto.recompile=true"
JAVA_OPTS="-server ${ODISEE_JVM_MEMORY} ${ODISEE_JVM_GC} -Djava.awt.headless=true ${ODISEE_TOMCAT_OPTS}"

#
# Watchdog.
#

# Watchdog timeout for checks
declare -i WD_TIMEOUT=5

#
# Options.
#

# Odisee Extensions
ODISEE_EXT_VND="vnd.artofcoding.odisee.Odisee"

#
# Exports.
#

# Odisee
export ODISEE_CONF
export ODISEE_INST
export ODISEE_VAR
export ODISEE_LOG
export ODISEE_TMP
export ODISEE_BACKUP_RAMDISK
export ODISEE_OOO_USERINST
export ODISEE_EXT
# Java, Groovy, Grails
export JAVA_HOME
export ANT_HOME
export GROOVY_HOME
export GRAILS_HOME
export CATALINA_HOME
# The path
PATH=${ODISEE_HOME}/bin:${ODISEE_HOME}/libexec/${ODISEE_OS}/${ODISEE_ARCH}/bin:${ANT_HOME}/bin:${JAVA_HOME}/bin:${GRAILS_HOME}/bin:${GROOVY_HOME}/bin:${PATH}
export PATH

# Include local configuration
. ${ODISEE_CONF}/local.odienv
