#!/usr/bin/env bash
# 
# Odisee(R)
# Copyright (C) 2011-2014 art of coding UG (haftungsbeschränkt).
# Copyright (C) 2005-2010 Informationssysteme Ralf Bensmann.
#
# Alle Rechte vorbehalten. Nutzung unterliegt Lizenzbedingungen.
# All rights reserved. Use is subject to license terms.
# 

#
# PLEASE DON'T CHANGE LINES BELOW
# UNLESS ADVISED BY Odisee SUPPORT
#

# Determine script directory
case "$0" in
    ./*) SCRIPT_DIR=${PWD} ;;
    /*) SCRIPT_DIR=${0%/*} ;;
    */*) SCRIPT_DIR=${PWD}/${0%/*} ;;
    *) SCRIPT_DIR=${PWD} ;;
esac

#
# Directories.
#

if [ x"${ODISEE_HOME}" = x"" ]
then
    echo "Please set ODISEE_HOME"
    exit 1
fi

# Odisee
ODISEE_LIBEXEC=${ODISEE_HOME}/libexec
ODISEE_ETC=${ODISEE_HOME}/etc
ODISEE_INST=${ODISEE_ETC}/odiinst
ODISEE_OS_LIB=${ODISEE_LIBEXEC}/${ODISEE_OS}
ODISEE_VAR=${ODISEE_HOME}/var
ODISEE_LOG=${ODISEE_VAR}/log
ODISEE_USER=${ODISEE_VAR}/user
ODISEE_USER_PROFILE=${ODISEE_VAR}/profile
ODISEE_TMP=${ODISEE_VAR}/tmp
ODISEE_TMP_RAMDISK_MB=${ODISEE_TMP_RAMDISK_MB:-16}
ODISEE_BACKUP=${ODISEE_VAR}/backup
ODISEE_SRC=${ODISEE_HOME}/src
ODISEE_EXT=${ODISEE_SRC}/extension

#
# Operating system.
#

ODISEE_FQHN=$(uname -n)
ODISEE_OS=$(uname -s)
ODISEE_ARCH=$(uname -m)

# OS-dependent
case "${ODISEE_OS}" in
    Darwin)
        SED=$(which gsed)
    ;;
esac

# Any OS
SED=${SED:-$(which sed)}
RSYNC=${RSYNC:-$(which rsync)}
SUDO=${SUDO:-$(which sudo)}
CURL=${CURL:-$(which curl)}

# Check needed executables
_check_exeutable() {
    local n=$1
    local e=$2
    local msg=""
    if [ -n "${e}" ]
    then
        if [ ! -x ${e} ]
        then
            msg="ODI-xxx: Needed executable '${n}' not executable by $(whoami)."
        fi
    else
        msg="ODI-xxx: Needed executable '${n}' not found"
    fi
    [ -n "${msg}" ] && echo ${msg}
}
_check_exeutable sed ${SED}
_check_exeutable rsync ${RSYNC}
_check_exeutable sudo ${SUDO}
_check_exeutable sudo ${CURL}
unset -f _check_executable

#
# Check .fonts directory
#
fonts=${ODISEE_HOME}/.fonts
if [ ! -h "${fonts}" ] # does not exist
then
    ln -s ${ODISEE_HOME}/var/deploy/font ${fonts} 
fi

#
# Java
#

# Get JAVA_HOME
if [ -z "${JAVA_HOME}" ]
then
    case "${ODISEE_OS}" in
        Darwin)
            JAVA_HOME=$(/usr/libexec/java_home)
        ;;
        *)
            JAVA_HOME=$(which java)
            JAVA_HOME=${JAVA_HOME%/bin/java}
        ;;
    esac
    # Fallback is libexec/os/arch/java
    if [[ -d ${ODISEE_LIBEXEC}/jdk1.7.0 ]]
    then
        JAVA_HOME=${JAVA_HOME:-$ODISEE_LIBEXEC/jdk1.7.0}
    fi
    echo "WARN: Automatically discovered JAVA_HOME=${JAVA_HOME}"
fi
# Check if we can execute java
[ ! -x ${JAVA_HOME}/bin/java ] && unset JAVA_HOME

# Apache Ant
ANT_HOME=${ANT_HOME:-$ODISEE_LIBEXEC/ant}

# Apache Tomcat
CATALINA_BASE=${CATALINA_BASE:-$ODISEE_LIBEXEC/tomcat}

#
# Watchdog.
#

# Watchdog timeout for checks
ODISEE_WD_TIMEOUT=5

#
# Options.
#

# Odisee Extensions
ODISEE_EXT_VND="vnd.artofcoding.odisee.Odisee"

#
# Exports.
#

# Odisee
export ODISEE_ETC
export ODISEE_INST
export ODISEE_VAR
export ODISEE_LOG
export ODISEE_TMP
export ODISEE_BACKUP
export ODISEE_USER_PROFILE
export ODISEE_EXT
export ODISEE_WD_TIMEOUT
# Java, Groovy, Grails
export JAVA_HOME
export ANT_HOME
export CATALINA_HOME
# The path
PATH=${ODISEE_HOME}/bin:${ODISEE_HOME}/libexec/${ODISEE_OS}/${ODISEE_ARCH}/bin:${ANT_HOME}/bin:${JAVA_HOME}/bin:${PATH}
export PATH

# Include local configuration
. ${ODISEE_ETC}/local.odienv
